#!/usr/bin/env bash
# Displays "I am invincible!!!" when receiving a sigterm signal 

terminate() {
	echo "I am invincible!!!"
}

trap terminate SIGTERM

while true
do
	echo "I am invincible!!!"
	sleep 2
done
